export { apiClient, ApiError, firstFieldError, getApiErrorMessage } from '@/services/http.ts'
export type { ApiEnvelope, ApiErrorBag, AuthPayload, ProfilePayload } from '@/services/types.ts'
export { queryKeys } from '@/services/queryKeys.ts'
export { getProfile, login, logout, register } from '@/services/auth.service.ts'
export { getOccasions, getPricingPlans, getTemplate, getTemplates } from '@/services/catalog.service.ts'
export { createProject, getProject, getProjects, updateProject } from '@/services/projects.service.ts'
export { fetchProjectUploads, uploadProjectMedia, fetchTemplateUploads, uploadTemplateMedia } from '@/services/uploads.service.ts'
export { deleteAdminTemplate, deleteAdminUser, fetchAdminTemplates, fetchAdminUsers, getAdminStats, getAdminWishes, updateAdminTemplate, updateAdminUser, createAdminTemplate } from '@/services/admin.service.ts'
